# Generated by Django 5.1.1 on 2024-11-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_item_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default="2024-01-01"
),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='grand_parent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='minor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
