# Generated by Django 5.1.1 on 2024-11-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_item_date_userinfo_grand_parent_userinfo_minor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
