# Generated by Django 5.1.1 on 2024-12-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.userinfo'),
        ),
    ]
