# Generated by Django 5.1.1 on 2024-12-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_item_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='registered',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
